### ISSUE TITLE
License info missing

### ISSUE THREAD

**Issue by 1c3f0x84** [jgiacomini/Tiny.RestClient#104]
Hello,
i would like to use Tiny.RestClient in our project, but there is no license info.

**Comment by jgiacomini** [comment]
Hello,
Not sure which license  to choose.
Have you any reommandation ?

**Comment by 1c3f0x84** [comment]
https://tldrlegal.com/license/mit-license :D

**Comment by jgiacomini** [comment]
OK I am adding it :)

**Comment by jgiacomini** [comment]
https://github.com/jgiacomini/Tiny.RestClient/pull/106

**Comment by jgiacomini** [comment]
Done :)

**Comment by 1c3f0x84** [comment]
Awesome 👍
