### ISSUE TITLE
JSON Fuzzy element name matching

### ISSUE THREAD

**Issue by daniel-luberda** [jgiacomini/Tiny.RestClient#45]
Fuzzy element name matching would be a great addition.
- 'product_id' in XML/JSON will match C# property named 'ProductId'
- etc

**Comment by jgiacomini** [comment]
Hello,

You can personalize the two serializers to achieve this type of matching.

The second possibility is to add attribute like [JsonProperty("release_date")].

If you want to add this feature (add some configuration for formatters), feel free to make a PR :).

**Comment by jgiacomini** [comment]
@daniel-luberda can you tell me if the implementation I made was what you imagine?
