### ISSUE TITLE
Add support for call rate limits

### ISSUE THREAD

**Issue by jonathanantoine** [jgiacomini/Tiny.RestClient#76]
For example, accepts only 40 requests by  / 10 seconds.

Thank you.

**Comment by jonathanantoine** [comment]
Something like in this nice article I found on the web ? https://blogs.infinitesquare.com/posts/windows/definir-le-nombre-maximum-de-requetes-faite-a-votre-serveur-par-plage-de-temps

**Comment by jonathanantoine** [comment]
Very nice idea, i look forward to see this implemented

**Comment by jgiacomini** [comment]
Hello,

I will think about it
