### ISSUE TITLE
Http librairie should not through http exception 

### ISSUE THREAD

**Issue by guillaumechervetaxa** [jgiacomini/Tiny.RestClient#80]
Hi,

I think that this libraries should not through exception when http 400 code is returned. The status code is an information not a crash. It is the same for 500 status code. The response can contain useful information. The exception behavior intricate the code behind. It is the consumer choice to through an Exception or not and that depends of your needs.

What do you think about? 

Regards,

**Comment by malotho** [comment]
Definitely, the user should decide whether to they throw an exception or not.

**Comment by jgiacomini** [comment]
Hello Guilllaume,

When server has an http code 400 or 500 the response have ont the same format.
It's why I throw exceptions un this case.

Can you give me some example where it s not the case?

**Comment by jgiacomini** [comment]
Hello,

I open to discuss about it.
But for me when server throw a status 400 or 500 the response have not the same format.
It's I throw an exception. 

On httpexception on this case you have a property named content with the body on the server response.

**Comment by jgiacomini** [comment]
@guillaumechervetaxa I thought about this feature I am working on it.

**Comment by guillaumechervetaxa** [comment]
You can look at this implementation that look good => https://developer.mozilla.org/fr/docs/Web/API/Fetch_API/Using_Fetch

Your library will be more usable in  functional/declarative way (all the language evolve in this way) when you will remove exception

**Comment by jgiacomini** [comment]
@guillaumechervetaxa  you can start to read what I start to implement in this PR =>#81.

**Comment by jgiacomini** [comment]
It's done in 1.7.0
