### ISSUE TITLE
AddFileContent Using MultipartFormDataStreamProvider

### ISSUE THREAD

**Issue by aboah** [jgiacomini/Tiny.RestClient#88]
Hello
Please How can Developers **upload files of application/octet-stream** with Tiny.RestClient 
Using **Web Api MultipartFormDataStreamProvider**

Can you show us a working Example

**Comment by jgiacomini** [comment]
Hello, 

You can do it like that =>
```
var response = await client.
                PostRequest("City/Image/Add").
                AsMultiPartFromDataRequest().
                AddFileContent(fileInfo1, "text/plain").
                AddFileContent(fileInfo2, "text/plain").
                ExecuteAsync<Response>();
```

If you prefer use byte array the syntax is :
