### ISSUE TITLE
specifiying BindIPEndPointDelegate?

### ISSUE THREAD

**Issue by bonesoul** [jgiacomini/Tiny.RestClient#94]
does tiny.restclient support specifiying the local ip address to use while making the requests?

**Comment by jgiacomini** [comment]
If use use HttpClient internally if you use a personalize the ServicePointManager. I think it's will be compatible :)

**Comment by bonesoul** [comment]
but i guess that's not possible with dotnet core.

**Comment by jgiacomini** [comment]
I have to check that point :)

**Comment by jgiacomini** [comment]
It's seem ServicePointManager is available in .NET Core from v2.0

https://stackoverflow.com/questions/39560249/servicepointmanager-in-asp-net-core

**Comment by bonesoul** [comment]
but seems ServicePoint.BindIPEndPointDelegate is not working yet https://github.com/dotnet/corefx/issues/23426
